# Generated by Django 5.1 on 2024-08-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL')], max_length=4)),
                ('material', models.CharField(choices=[('cotton', 'Cotton'), ('jeans', 'Jeans'), ('deim', 'Deim'), ('woollen', 'Woollen'), ('nylone', 'Nylone'), ('synthetic', 'Synthetic'), ('mix', 'Mix')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothes/')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('similar_clothes', models.ManyToManyField(blank=True, to='clothes.cloth')),
            ],
        ),
    ]
