# Generated by Django 5.1 on 2024-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to='clothes/images/'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='material',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('jeans', 'Jeans'), ('denim', 'Denim'), ('woollen', 'Woollen'), ('nylon', 'Nylon'), ('synthetic', 'Synthetic'), ('mix', 'Mix')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], max_length=10),
        ),
    ]
