# Generated by Django 5.1 on 2024-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_cloth_image_alter_cloth_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='material',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Jeans', 'Jeans'), ('Denim', 'Denim'), ('Woollen', 'Woollen'), ('Nylon', 'Nylon'), ('Synthetic', 'Synthetic'), ('Mix', 'Mix')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10),
        ),
    ]
