# Generated by Django 5.1 on 2024-08-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_cloth_image_alter_cloth_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='similar_clothes',
        ),
        migrations.AlterField(
            model_name='cloth',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to='cloth_images/'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='material',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('jeans', 'Jeans'), ('denim', 'Denim'), ('woollen', 'Woollen'), ('nylon', 'Nylon'), ('synthetic', 'Synthetic'), ('mix', 'Mix')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
