# Generated by Django 5.1 on 2024-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_remove_cloth_similar_clothes_alter_cloth_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotton_weight', models.FloatField(default=0.0)),
                ('jeans_weight', models.FloatField(default=0.0)),
                ('woollen_weight', models.FloatField(default=0.0)),
                ('nylon_weight', models.FloatField(default=0.0)),
                ('synthetic_weight', models.FloatField(default=0.0)),
                ('mix_weight', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
